import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const generatedApiSidebarCategory = {
    className: "sb-cat-api-overview",
    collapsed: false,
    items: [
        {
            dirName: "developer/api",
            type: "autogenerated" as const,
        },
    ],
    label: "📘 API",
    link: {
        description:
            "Generated API documentation for the plugin runtime and internal helpers.",
        title: "API",
        type: "generated-index" as const,
    },
    type: "category" as const,
};

/** Main sidebar configuration for the primary documentation section. */
const sidebars = {
    docs: [
        {
            className: "sb-doc-developer",
            id: "developer/index",
            label: "Developer Docs",
            type: "doc",
        },
        {
            className: "sb-doc-site-contract",
            id: "developer/docusaurus-site-contract",
            label: "🧭 Docs Site Contract",
            type: "doc",
        },
        generatedApiSidebarCategory,
    ],
} satisfies SidebarsConfig;

export default sidebars;
